services:
  - type: web
    name: digital-library-demo
    runtime: python
    rootDir: .
    buildCommand: ./build.sh
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 2
